PUT http://localhost:8080/api/app-visibility-v1/schema
Content-Type: application/json

{
  "default_priority": 0,
  "default_sla": 43200,
  "retry_policy": { "max_attempts": 3 },
  "hooks": {
    "result": "https://app/api/batch/result",
    "refresh": "https://app/api/batch/refresh"
  }
}

###

PUT http://localhost:8080/api/app-visibility-v1/tasks/GPTTASK123
Content-Type: application/json

{
  "model": "gpt-3.5-turbo",
  "max_tokens": 500,
  "temperature": 0.7,
  "messages": [
    { "role": "system", "content": "foo" },
    { "role": "user", "content": "bar" },
    { "role": "user", "content": "baz" }
  ],

  "priority": 2,
  "sla": 43200
}
