// Code generated by mockery v2.53.3. DO NOT EDIT.

package providers

import (
	context "context"

	resources "github.com/eser/bfo/pkg/api/business/resources"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Provider type
type MockClient struct {
	mock.Mock
}

// CancelBatch provides a mock function with given fields: ctx, batchId
func (_m *MockClient) CancelBatch(ctx context.Context, batchId string) (*resources.Batch, error) {
	ret := _m.Called(ctx, batchId)

	if len(ret) == 0 {
		panic("no return value specified for CancelBatch")
	}

	var r0 *resources.Batch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*resources.Batch, error)); ok {
		return rf(ctx, batchId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *resources.Batch); ok {
		r0 = rf(ctx, batchId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resources.Batch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, batchId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateBatch provides a mock function with given fields: ctx, batchReq
func (_m *MockClient) CreateBatch(ctx context.Context, batchReq resources.CreateBatchRequest) (*resources.Batch, error) {
	ret := _m.Called(ctx, batchReq)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 *resources.Batch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, resources.CreateBatchRequest) (*resources.Batch, error)); ok {
		return rf(ctx, batchReq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, resources.CreateBatchRequest) *resources.Batch); ok {
		r0 = rf(ctx, batchReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resources.Batch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, resources.CreateBatchRequest) error); ok {
		r1 = rf(ctx, batchReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateFile provides a mock function with given fields: ctx, filePath, purpose
func (_m *MockClient) CreateFile(ctx context.Context, filePath string, purpose string) (*resources.File, error) {
	ret := _m.Called(ctx, filePath, purpose)

	if len(ret) == 0 {
		panic("no return value specified for CreateFile")
	}

	var r0 *resources.File
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*resources.File, error)); ok {
		return rf(ctx, filePath, purpose)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *resources.File); ok {
		r0 = rf(ctx, filePath, purpose)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resources.File)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, filePath, purpose)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBatches provides a mock function with given fields: ctx, params
func (_m *MockClient) ListBatches(ctx context.Context, params *resources.ListBatchesParams) (*resources.ListBatchesResponse, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListBatches")
	}

	var r0 *resources.ListBatchesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *resources.ListBatchesParams) (*resources.ListBatchesResponse, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *resources.ListBatchesParams) *resources.ListBatchesResponse); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resources.ListBatchesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *resources.ListBatchesParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveBatch provides a mock function with given fields: ctx, batchId
func (_m *MockClient) RetrieveBatch(ctx context.Context, batchId string) (*resources.Batch, error) {
	ret := _m.Called(ctx, batchId)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveBatch")
	}

	var r0 *resources.Batch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*resources.Batch, error)); ok {
		return rf(ctx, batchId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *resources.Batch); ok {
		r0 = rf(ctx, batchId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resources.Batch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, batchId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
